import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';

import 'package:pipstats/solscan_service.dart';

/// Golden tests for the Metaplex Token Metadata decoder, against **real
/// mainnet accounts** fetched from `api.mainnet-beta.solana.com` on
/// 2026-09-23 (`encoding: "base64"`).
///
/// This decoder replaces Helius DAS for token names and symbols: it reads the
/// metadata account directly, so it works on any RPC with no API key.
void main() {
  group('TokenMetadata.decode — real mainnet accounts', () {
    test('SKR (Seeker)', () {
      // metadata PDA J753AwzZP1mrHgnfuujQTd7a3jEWQaUCzskMxLwsVYVj
      const data = 'BPff0ZgViKFCpwQiaac97Q9yoqptfcBpTa38aqOfCp8jBnxaPgX+QUcSp6Lq/kK+dhC82Qy/VxYndYNzy4rQ2KQgAAAAU2Vla2VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAU0tSAAAAAAAAAMgAAABodHRwczovL3IyLnNvbGFuYW1vYmlsZWRhcHBzdG9yZS5jb20vc2tyL21ldGFkYXRhLmpzb24AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAf0BAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';
      final meta = TokenMetadata.decode(base64Decode(data))!;
      expect(meta.name, 'Seeker');
      expect(meta.symbol, 'SKR');
      expect(meta.uri, contains('solanamobiledappstore.com'));
    });

    test('JitoSOL', () {
      // metadata PDA 8yn5oqFMwYA8SgGqWwKq1Hia8aM5gh1DWmHEL34hMqBX
      const data = 'BMRMC0OCUN+z22qnNe6j9AhUAxTVLRTZvX0pK6xUPI62/NFB6YMsrxCtkXSVyg8nG1spPNRwJ+pzcAftQOs5oL0gAAAASml0byBTdGFrZWQgU09MAAAAAAAAAAAAAAAAAAAAAAAKAAAASml0b1NPTAAAAMgAAABodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdG9rZW4tbWV0YWRhdGEvSml0b1NPTC5qc29uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAfwBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';
      final meta = TokenMetadata.decode(base64Decode(data))!;
      expect(meta.name, 'Jito Staked SOL');
      expect(meta.symbol, 'JitoSOL');
    });

    test('trailing NUL padding is trimmed', () {
      const data = 'BPff0ZgViKFCpwQiaac97Q9yoqptfcBpTa38aqOfCp8jBnxaPgX+QUcSp6Lq/kK+dhC82Qy/VxYndYNzy4rQ2KQgAAAAU2Vla2VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAU0tSAAAAAAAAAMgAAABodHRwczovL3IyLnNvbGFuYW1vYmlsZWRhcHBzdG9yZS5jb20vc2tyL21ldGFkYXRhLmpzb24AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAf0BAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';
      final meta = TokenMetadata.decode(base64Decode(data))!;
      // Metaplex pads name to 32 bytes and symbol to 10; a decoder that keeps
      // the padding renders as "Seeker\u0000\u0000..." in the UI.
      expect(meta.name, isNot(contains('\u0000')));
      expect(meta.symbol, isNot(contains('\u0000')));
      expect(meta.name.length, 'Seeker'.length);
    });

    test('garbage and short buffers decode to null, not a crash', () {
      expect(TokenMetadata.decode(base64Decode('AAAA')), isNull);
      expect(TokenMetadata.decode(base64Decode('')), isNull);
    });
  });
}
